config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'

  root 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

# devise parameters use permit in place of for
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcade</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>

    <%= render partial: "shared/header" %>
    <%= render partial: "shared/message" %>

  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>

    <%= render partial: "shared/footer" %>

  </body>

<script>
  $(".button-collapse").sideNav();
  $(".dropdown-button").dropdown();
</script>

</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer green lighten-2">
   <div class="container">
     <div class="row">
       <div class="col l6 s12">
         <h5 class="white-text">Creator Arcade</h5>
         <p class="grey-text text-lighten-4">Project based learning for music producers.</p>
       </div>
       <div class="col l4 offset-l2 s12">
         <h5 class="white-text">Look at our dab.</h5>
         <ul>
           <li><a class="grey-text text-lighten-3" href="#!">Snapchat</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
         </ul>
       </div>
     </div>
   </div>
   <div class="footer-copyright">
     <div class="container">
     © 2017 Creator Arcade
     <%= link_to "About Creator Arcade", pages_about_path, :class => "grey-text text-lighten-4 right" %>
     </div>
   </div>
 </footer>

app/views/shared/_header.html.erb
<header>

  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <!-- edit_user_registration_path links the profile to the path we defined in views/devise/registrations/edit.html.erb -->
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><a href="#!">Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  </ul>

  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><a href="#!">Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  </ul>


  <nav class="green lighten-2 z-depth-2">
    <div class="container">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Creator Arcade</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="#">Courses</a></li>
          <% if(!user_signed_in?) %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
              <%= current_user.name %><i class="medium material-icons
            right">arrow_drop_down</i></a></li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="#">Courses</a></li>
          <% if(!user_signed_in?) %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
              <%= current_user.name %><i class="medium material-icons
            right">arrow_drop_down</i></a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>